# fly.toml app configuration file generated for cookiebot on 2023-10-02T16:56:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cookiebot"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
